import { describe,it,expect } from 'vitest';
import { parseArtifact, validateValues } from '../../src/contracts/artifact.js';
import { resolveBindings } from '../../src/replay/bindings.js';
const schema={type:'object',properties:{email:{type:'string',format:'email'},enabled:{type:'boolean',default:true}},required:['email'],additionalProperties:false};
export const definition={surface:'browser',compatibility:{product_id:'desk',ui_variant:'standard',vendor_release:null},input_schema:schema,output_schema:{type:'object',properties:{status:{type:'string'}},required:['status'],additionalProperties:false},entry:{url:{kind:'environment',path:'base_url'},checks:[]},steps:[{step_id:'s1',tool:'extract_data',arguments:{fields:[{name:'status',target:{kind:'semantic',role:'text',name:{kind:'literal',value:'Active'},exact:true,scope:null,required_matches:1},property:'text',output_type:'string'}]},pre_checks:[],post_checks:[],recoveries:[]}],success_checks:[{check_id:'success',kind:'tool_status_equals',step_id:'s1',expected:'completed'}],business_outcomes:[],output_mapping:{status:{kind:'step_output',step_id:'s1',path:'fields.status.value'}}};
describe('durable artifact',()=>{
 it('preserves primitive types and resolves declared bindings',()=>{expect(parseArtifact(definition).steps).toHaveLength(1);expect(validateValues(schema,{email:'a@example.test'})).toEqual({email:'a@example.test',enabled:true});expect(resolveBindings({kind:'input',path:'enabled'},{enabled:false},{},{base_url:'http://localhost'})).toBe(false);expect(()=>validateValues(schema,{email:'bad'})).toThrow();});
 it('rejects stale refs, forward refs, duplicate IDs and absolute URLs',()=>{for(const mutation of [ {...definition,steps:[{...definition.steps[0],arguments:{control_ref:'c1'}}]}, {...definition,steps:[definition.steps[0],definition.steps[0]]}, {...definition,steps:[{...definition.steps[0],arguments:{value:{kind:'step_output',step_id:'s1',path:'x'}}}]}, {...definition,entry:{url:{kind:'literal',value:'https://tenant.test'},checks:[]}}]) expect(()=>parseArtifact(mutation)).toThrow();});
});
